#include "obj_writer.h"
#include <iostream>
#include <fstream>

OBJWriter::OBJWriter() {}

// Экспорт карты глубины в файл формата OBJ
bool OBJWriter::writeToOBJ(const std::string& filename,
    const std::vector<std::vector<double>>& depthData,
    double scale) {
    if (depthData.empty()) {
        std::cerr << "Ошибка: Нет данных для записи" << std::endl;
        return false;
    }

    std::ofstream file(filename);
    if (!file.is_open()) {
        std::cerr << "Ошибка: Не удалось создать файл " << filename << std::endl;
        return false;
    }

    writeHeader(file);
    writeVertices(file, depthData, scale);
    writeFaces(file, depthData);

    file.close();
    std::cout << "3D модель успешно экспортирована в " << filename << std::endl;
    return true;
}

void OBJWriter::writeHeader(std::ofstream& file) {
    file << "# 3D Model from Depth Map\n";
    file << "# Generated by Lab3 City Model Converter\n\n";
}

// Запись вершин 3D модели
void OBJWriter::writeVertices(std::ofstream& file,
    const std::vector<std::vector<double>>& depthData,
    double scale) {
    int height = depthData.size();
    int width = depthData[0].size();

    file << "# Vertices\n";
    for (int i = 0; i < height; i++) {
        for (int j = 0; j < width; j++) {
            // Преобразование координат с центрированием и масштабированием
            double x = (j - width / 2.0) * scale;
            double y = depthData[i][j] * scale; // Высота = значение глубины
            double z = (i - height / 2.0) * scale;
            file << "v " << x << " " << y << " " << z << "\n";
        }
    }
    file << "\n";
}

// Запись полигонов (треугольников) 3D модели
void OBJWriter::writeFaces(std::ofstream& file,
    const std::vector<std::vector<double>>& depthData) {
    int height = depthData.size();
    int width = depthData[0].size();

    file << "# Faces\n";
    for (int i = 0; i < height - 1; i++) {
        for (int j = 0; j < width - 1; j++) {
            // Индексы вершин для двух треугольников, образующих квадрат
            int v1 = i * width + j + 1;
            int v2 = i * width + j + 2;
            int v3 = (i + 1) * width + j + 1;
            int v4 = (i + 1) * width + j + 2;

            // Два треугольника для каждого квадрата сетки
            file << "f " << v1 << " " << v2 << " " << v3 << "\n";
            file << "f " << v2 << " " << v4 << " " << v3 << "\n";
        }
    }
}